// Generated by BUCKLESCRIPT VERSION 1.8.0, PLEASE EDIT WITH CARE
'use strict';


var tagApi = "https://api.stackexchange.com/2.2/tags?order=desc&sort=popular&site=stackoverflow";

var tags = fetch(tagApi).then((function (prim) {
          return prim.text();
        })).then((function (text) {
        return Promise.resolve((console.log(text), /* () */0));
      }));

exports.tagApi = tagApi;
exports.tags   = tags;
/* tags Not a pure module */
