// Generated by BUCKLESCRIPT VERSION 1.8.0, PLEASE EDIT WITH CARE
'use strict';

var Request = require("request");

var Body = /* module */[];

var Response = /* module */[];

function get(uri) {
  return Request.get(uri).on("response", (function (response) {
                console.log(response.statusCode);
                return /* () */0;
              }));
}

function post(uri, data) {
  return Request.post(uri, data);
}

exports.Body     = Body;
exports.Response = Response;
exports.get      = get;
exports.post     = post;
/* request Not a pure module */
